<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNrjntfh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNrjntfh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNrjntfh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNrjntfh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNrjntfh\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Nrjntfh',
    'container.build_id' => '6920ac61',
    'container.build_time' => 1524088387,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNrjntfh');
