<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC4tvd96\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC4tvd96/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerC4tvd96.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerC4tvd96\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerC4tvd96\appDevDebugProjectContainer(array(
    'container.build_hash' => 'C4tvd96',
    'container.build_id' => '383068cd',
    'container.build_time' => 1524157641,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerC4tvd96');
